// import {
//     GET_CONSTRUCTOR_INGREDIENT,
//     ADD_CONSTRUCTOR_INGREDIENT,
//     DELETE_CONSTRUCTOR_INGREDIENT,
//     RESET_CONSTRUCTOR,
//     SWAP_CONSTRUCTOR_INGREDIENT
// } from '../constants/actionTypes';