export const ADD_CONSTRUCTOR_INGREDIENT = "ADD_CONSTRUCTOR_INGREDIENT";
export const DELETE_CONSTRUCTOR_INGREDIENT = "DELETE_CONSTRUCTOR_INGREDIENT"
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR"
export const GET_CONSTRUCTOR_INGREDIENT = "GET_CONSTRUCTOR_INGREDIENT"
export const SWAP_CONSTRUCTOR_INGREDIENT = "SWAP_CONSTRUCTOR_INGREDIENT"