export const ADD_CONSTRUCTOR_INGREDIENT = "ADD_CONSTRUCTOR_INGREDIENT" as const;
export const DELETE_CONSTRUCTOR_INGREDIENT = "DELETE_CONSTRUCTOR_INGREDIENT" as const;
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR" as const;
export const GET_CONSTRUCTOR_INGREDIENT = "GET_CONSTRUCTOR_INGREDIENT" as const;
export const SWAP_CONSTRUCTOR_INGREDIENT = "SWAP_CONSTRUCTOR_INGREDIENT" as const;
