export const SET_VIEW_ORDER = "SET_VIEW_ORDER";
export const RESET_VIEW_ORDER = "RESET_VIEW_ORDER";
export const GET_VIEW_ORDER_REQUEST = "GET_VIEW_ORDER_REQUEST";
export const GET_VIEW_ORDER_SUCCESS = "GET_VIEW_ORDER_SUCCESS";
export const GET_VIEW_ORDER_FAILED = "GET_VIEW_ORDER_FAILED";
export const SET_VIEW_ORDER_ERROR = "SET_VIEW_ORDER_ERROR";
