export const WS_SIGN_CONNECTION_START = "WS_SIGN_CONNECTION_START";
export const WS_SIGN_CONNECTION_STOP = "WS_SIGN_CONNECTION_STOP";
export const WS_SIGN_CONNECTION_SUCCESS = "WS_SIGN_CONNECTION_SUCCESS";
export const WS_SIGN_CONNECTION_ERROR = "WS_SIGN_CONNECTION_ERROR";
export const WS_SIGN_CONNECTION_CLOSED = "WS_SIGN_CONNECTION_CLOSED";
export const WS_SIGN_GET_MESSAGE = "WS_SIGN_GET_MESSAGE";
export const WS_SIGN_SEND_MESSAGE = "WS_SIGN_SEND_MESSAGE";