export const WS_SIGN_CONNECTION_START = "WS_SIGN_CONNECTION_START" as const;
export const WS_SIGN_CONNECTION_STOP = "WS_SIGN_CONNECTION_STOP" as const;
export const WS_SIGN_CONNECTION_SUCCESS = "WS_SIGN_CONNECTION_SUCCESS" as const;
export const WS_SIGN_CONNECTION_ERROR = "WS_SIGN_CONNECTION_ERROR" as const;
export const WS_SIGN_CONNECTION_CLOSED = "WS_SIGN_CONNECTION_CLOSED" as const;
export const WS_SIGN_GET_MESSAGE = "WS_SIGN_GET_MESSAGE" as const;
export const WS_SIGN_SEND_MESSAGE = "WS_SIGN_SEND_MESSAGE" as const;
